spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.73:8848

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"